### ISSUE TITLE
Clicking reference did not work

### ISSUE THREAD

**Issue by Avol-V** [qrti/funcList#1] opened 2017-08-18 11:17 UTC
Clicks just place cursor and do nothing.

My settings is:

```
"funcList.nativeFilter": "/(?:^|\\s)function\\s+\\w+\\(/mg",
"funcList.displayFilter": "/\\s*function\\s+(\\w+)/1",
```

Tested on ts and php files.

**Comment by qrti** [comment] 2017-08-31 07:26
The given native filter regexp generates leading carriage returns, funcList wasn't prepared for this, and therefore could not find references because they are evaluated line by line. Should be fixed with version 0.6.1.

In a first attempt I couldn't reproduce the issue, strange enough all worked well on single opened files and only on opened (project) folders the problem appeared.

**Closed as completed** 2017-09-23 07:03 UTC

**Comment by Avol-V** [comment] 2017-09-25 10:39
But it’s still did not work, even for single opened file.

**Comment by piotrku** [comment] 2017-09-29 09:04
doesn't work for me too - using version 7.0.0

tested on a PHP file with:
"funcList.nativeFilter": "/(?:^|\\s)function\\s+\\w+\\(/mg"

functions are found but clicking on them does nothing
